% -------------------------------------------------------------------
%  Generated by MATLAB on 8-Jan-2025 23:03:24
%  MATLAB version: 23.2.0.2668659 (R2023b) Update 9
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

parte1 = saveVarsMat.parte1; % <1x1 mamfis> unsupported class

clear saveVarsMat;
